CompileFlags:
  Add: [-std=c++17, -Wall, -Wno-unused-variable]
  # Remove extra warnings specified in compile commands.
  # Single value is also acceptable, same as "Remove: [-mabi]"
  Compiler: g++
  Remove: [-fvar-tracking,-fvar-tracking-assignments]
Diagnostics:
  # Tweak Clang-Tidy checks.
  ClangTidy:
    Add: [clang-analyzer*, performance*, modernize*, readability*]
    Remove: [
      clang-analyzer-osx*,
      modernize-avoid-c-arrays,
      readability-identifier-length,
      readability-braces-around-statements,
      readability-implicit-bool-conversion,
      readability-isolate-declaration,
      modernize-use-trailing-return-type,
      modernize-use-nodiscard,
      modernize-use-using,
      modernize-use-auto,
      readability-redundant-access-specifiers,
      readability-function-cognitive-complexity,
      readability-magic-numbers,
      readability-uppercase-literal-suffix,
      readability-qualified-auto,
      readability-convert-member-functions-to-static
    ]
